---
title: "ESM 206 Assignment 4: Spiny Lobster Abundance"
author: "Jordan Faires"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Introduction*

*Methods*

*Results*


```{r}
# Load packages

library(tidyverse)
library(here)
library(janitor)

# Read in data, clean names

lobster_abundance <-read.csv("lobster_abundance_sbc_lter.csv",
  na = "-99999") %>% 
  clean_names()

# Make data tidy

lobster_tidy <- lobster_abundance %>% 
  tidyr::uncount(count)

```

Results A:

```{r}
# Group & summarize lobster data for each location by year

lobster_ysite <- lobster_tidy %>% 
  count(year, site) %>% 
  group_by(site)

ggplot(lobster_ysite, aes(x=year, y=n, group=site, color=site)) +
  geom_line() +
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "gray99", size = .1)) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "",
       y = "Annual Count",
       title = "Annual California Spiny Lobster Counts") +
    scale_color_discrete(breaks=c("AQUE", 
                                  "CARP", 
                                  "IVEE", 
                                  "MOHK", 
                                  "NAPL"),
                       labels=c("Arroyo Quemado", 
                                "Carpenteria", 
                                "Isla Vista (Marine Protected Area)", 
                                "Mohawk", 
                                "Naples (Marine Protected Area)")) +
  theme(legend.position = c(0.25, 0.65))


```

